on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
env:
  DOTNET_VERSION: 8.0

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup dotnet ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      shell: powershell
      run: |
        $ver="${{github.ref_name}}".Replace('v','')
        "VERSION=$ver" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - name: Build
      run: dotnet build --configuration Release -p:Version=$env:VERSION
    - name: Test
      run: dotnet test --configuration Release -p:Version=$env:VERSION --no-build
    - name: Pack
      run: nuget pack -Version $env:VERSION -Properties Configuration=Release -OutputDirectory .
    - name: Push
      run: dotnet nuget push IAUS-Net.$env:VERSION.nupkg --source https://nuget.pkg.github.com/SonarBeserk/index.json --api-key $env:GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}